### ISSUE TITLE
Invert evaluation metrics to make them easier to understand

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#709]
I think we can make evaluation metrics far simpler and easier to understand.

Right now, we have Algorithms and Metrics. Each metric then asks the test context for the results of something (recommendations, predictions, etc.), with aggressive caching so we don't recompute predictions and recommendations. But the metric is really driving things.  As a result, every Top-N metric needs to know how to control the recommender (list size, candidate set, etc.). There are a few metrics where the recommender needs to be called repeatedly, but these are rare.

Instead, we can introduce an intermediate conceptual layer of a *task*. The task can be something like:

- predict test ratings
- recommend 50 items from All \ TrainItems
- recommend 5 items from TestItems

The evaluator will then use the Algorithm to perform a Task, and provide the results of the Task to the Metric(s). A metric can then be simple: it receives data (prediction output, recommendation output) and produces results, without knowing how to drive recommenders. Different task types can have different metric types, in a clear fashion that doesn't merge the needs for Top-N and Predict in a single interface. We can also support custom tasks, replacing the fantastically confusing `MultiModelMetric`.

We can probably even inject the metrics, so they can get more direct access to recommender components (such as a popularity or tag genome model).

It might seem a little backwards, introducing another layer to simplify things, but I think it will be easier to write something like this:

```
dataset foo
dataset bar

algorithm apple
algorithm turtle

predict {
    measure RMSE
    measure MAE
}
recommend {
    items 10
    candidates AllItems
    exclude TrainingItems
    measure MAP(good: TestItems)
    measure MRR(good: TestItems)
}
extract {
    record ItemLatentFeatures
}
```

**Comment by kluver** [comment]
This will confuse people who are used to the old style. Any change in configuration files (notoriously hard to debug due to lack of useful reporting on failure) will confuse people. 

This sounds like a cool change, It makes things a lot more clear code-side and reduce redundancy. It also might support more complicated / obscure evaluations centered around tasks we couldn't even imagine.

This sounds really neat, but I wonder how much it buys us for the trouble. how often are people implementing metrics? How often do people find that difficult compared with the ease of copying a working metric for a given task and modifying it to serve their needs?

**Comment by elehack** [comment]
Every time I implement a metric, I wind up thinking 'why is this so difficult?' It's easier than it was, but pounding nails with a flat steel bar is easier than using a screwdriver. I find myself writing metrics with some regularity; as LensKit's metric suite expands, this should be less necessary, but how much of our research involves trying new ways of measuring things?

When I go to teach metric-writing (which we do in the RecSys assignments), I cringe.

There's also a lot of boilerplate that has to be there, and work the same (or clients will be confused!), but currently can't be abstracted. This is particularly in the builder/factory business, which really leaks a lot of the inner workings of the train-test eval onto the metric interface.

Also, our metric interfaces have to be sufficiently general to allow for both prediction, and recommendation, and everything else. With the task-based method, we can have an interface for each kind of metric, that makes it a *lot* more straightforward to implement a particular kind of metric (e.g. the predict metric can just take a user ID, test ratings, and predictions). We could even inject inject the metrics, allowing them to obtain recommender objects just like any other component does, rather than having a separate way of doing it for metrics and for components. This is an advantage I didn't really think about when writing the initial ticket.

It will be a compatibility/conversion issue. However, so many other things about evaluation configuration are going to change with LK 3, it seems like Just Another Thing we need to document (and we should write a LensKit 2->3 conversion guide).

**Comment by mdekstrand** [comment]
The new train-test evaluator uses this new design. The results seem pretty good IMO.
