### ISSUE TITLE
ItemScorer interface improvement

### ISSUE THREAD

**Issue by aleSuglia** [lenskit/lenskit#749]
Good morning,
I've started to work with Lenskit framework some days ago. Everything looks pretty well done and easy to implement thanks to the robust API.
Unfortunately, I'm having some problems in using the **ItemScorer** interface because I think that it's too *rigid*.
When I say *rigid* I mean that it cannot be used in some cases. In fact, items' id or users' id in our dataset are not long, but they are strings. 
I know that all the well known datasets use long values for identifiers, but I think that using a generalized interface could be appropriate in order to grant to everyone to use it, in every context.

I think that the **ItemScorer** could be modified with a generalized interface in this way:

     public ItemScorer<U, I> {
            @Override
            public double score(U user, I item) {
                 // ... other code ...
            }

           @Nonnull
           @Override
           public SparseVector score(U user, Collection<I> items) {
                    // ... other code ...
           }

          @Override
          public void score(U user, @Nonnull MutableSparseVector mutableSparseVector) {
                  // ... other code ...
          }
     }

Do you think that you can follow this approach or can break something else?

Thank you in advance for your answer.
Alessandro Suglia

**Comment by mdekstrand** [comment]
@aleSuglia Thanks for bringing this up!

We actually used a design like this in very early (0.2?) versions of LensKit. There are two downsides to it:

1. The common case of numeric identifiers becomes substantially slower and/or more memory intensive, since we have to box the identifiers in `Long` or `Integer` objects. LensKit became substantially faster when we switched to requiring `long` IDs.
2. Dependency injection and generics do not play particularly well together (they can be integrated, as Guice has shown, but when developing Grapht we decided that the trade-off for LensKit's use, at the time, was not worth it).

Item (1) was determined quite some years ago, when Java 7 was brand-new and we were mostly focused on Java 6 support. Java 7 and particularly 8 have done a lot to reduce the overhead of boxing. However, that overhead is not completely gone, particularly when we must store user or item identifiers for any period of time (a `Long` is at least 28 bytes on a 64-bit system, including the pointer to the object, while a `long` is only 8 bytes).

The current intended design for handling this kind of case is to introduce a new DAO type to map between numeric and non-numeric user and item IDs; it would have `getUserKeyById` and `getUserIdByKey` methods, and likewise for items. Code that calls the item scorer would then look up the user/item IDs for keys, and then do the reverse lookup to show things to users. Custom recommender components would likewise depend on the new DAO type to be able to convert between LensKit IDs and database keys.

Now, this does not play terribly well with MongoDB or CouchDB, where records are identified by UUIDs; it effectively means that either the LensKIt integration code must maintain a UUID <-> long mapping, or the data model must augment records with numeric IDs. This is decidedly sub-optimal.

I am not sure what the best solution is here.

**Comment by kluver** [comment]
@Ekstrand, how big of a dataset do you think we need to have before 
keeping most or all of the lookup table in memory is unreasonable? For 
most of the domains I tend to work in an O(I) and O(U) lookup table 
isn't too big of a deal.

Failing that, has anybody investigated using a good hashing function? 
(not guaranteed to work, but in a practical system, it would, with high 
probability, work well enough)

Another thought: What about a wrapper class for some of the core classes 
that takes a function from <T> to long (which could be a lookup table or 
a web call) and an implementation of ItemScorer (or whichever other 
interface might be interesting) and then automatically manages the 
translation?

~Kluver

**Comment by mdekstrand** [comment]
@kluver wrote:
> how big of a dataset do you think we need to have before keeping most or all of the lookup table in memory is unreasonable? For most of the domains I tend to work in an O(I) and O(U) lookup table isn't too big of a deal.

Pretty big. Mapping 40-character strings to longs is on the order 128 bytes per entry, so 1M user mappings would take around 120MiB.

> Failing that, has anybody investigated using a good hashing function? (not guaranteed to work, but in a practical system, it would, with high probability, work well enough)

I have thought about that. SHA1 sum, XOR various components into a long. Not sure how reliable that would be.

> Another thought: What about a wrapper class for some of the core classes that takes a function from <T> to long (which could be a lookup table or a web call) and an implementation of ItemScorer (or whichever other interface might be interesting) and then automatically manages the translation? 

A wrapper class on its own isn't quite enough, because we also need to de-wrap in the DAOs. However, that is a doable deal. We could even integrate the relevant code into `UserDAO` and `ItemDAO`, with default implementations using `Long` keys and box/unbox as the mapping operation.  The class design might be a little funny, though.

But: there are lots of places where we already map longs to ints to store things in arrays, etc. We could use that regime more consistently, and make the numbers an implementation detail. I am not sure what the performance implications of that would be. It would require a fairly invasive set of changes to DAOs, data representations (ratings), etc., but it might be worth it (and on Java 8, might not have that much of a perf hit!).

If we are ever going to consider this, LensKit 3 is the time.

**Comment by mdekstrand** [comment]
With the new data API (#845), we have a new approach for solving this kind of problem. We still use long IDs everywhere, but we have the ability for users and items to be arbitrary entities in the underlying data set. So we can look up a user (and get its other info) easily (and this can be cached), and we can also search for a user by some key (e.g. UUID) to get a long entity ID.
