### ISSUE TITLE
Move and rename cursors

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#769]
We need to move cursors into `lenskit-core`, since the data structures package is going away. While we are at it, I would like to consider renaming them, because ‘cursor’ is a somewhat overloaded term (that I may actually want to use for something else, that's really more like a database cursor).

I have found a class in the Java standard library that is very similar to our cursors in most respects: [DirectoryStream](http://docs.oracle.com/javase/8/docs/api/java/nio/file/DirectoryStream.html) (OK, all respects, but C3PO)

I think that it would be reasonable to rename `Cursor` to `ObjectStream`, and move it to `o.l.util.streams` (or `o.l.io.streams`?). This would also make it consistent with our DAO naming: a `streamEvents` call will return an `ObjectStream`. There's a slight overloading with Java 8's streams, but Java already has that between DirectoryStream and Stream. I don't think it is a significant problem.

**Comment by mdekstrand** [comment]
Done in #772.

**Comment by mdekstrand** [comment]
ping @kluver - if you have any objections to this naming, or alternate suggestions, it'd be good to hear them early :)

**Comment by kluver** [comment]
I don't have any alternative suggestions. Ive never been entirely clear why
these arn't just iterators, but I suppose the closing requirement is a
pedantic but meaningful separation because it means that these can't be
dropped into normal iteration idoms.

I also don't understand why iterators don't implement iterable. But that's
neither here nor there.
ObjectStream sounds as good as anything else.

~kluver

**Comment by mdekstrand** [comment]
@kluver Ok.

I've also retooled `ObjectStream` a so it behaves more like an input stream (has a `readObject` method), but also implements `Iterable` so that it can be iterated conveniently.
