### ISSUE TITLE
The more evaluation metrics the longer evaluation

### ISSUE THREAD

**Issue by Bionic1251** [lenskit/lenskit#851]
In Lenskit 2.2.1, each evaluation metric require recommendation algorithm to generate recommendations, which increases evaluation time. For example, if I need to measure ndcg at 1, 3, 5, 10, 15, I have to add 5 NDCG metrics. Each metric would make recommender to score items.
Generated scores could be reused, which would shorten the evaluation time.

**Comment by mdekstrand** [comment]
Thank you for reporting this.

You can avoid recomputing the scores by using the `SimpleCachingItemScorer`:

```groovy
bind ItemScorer to SimpleCachingItemScorer
at (SimpleCachingItemScorer) {
    bind ItemScorer to ActualItemScorerImpl
}
```

This will cause subsequent recommendation operations for the same user (the common case in an evaluation) to reuse the item scores from the last pass, significantly speeding up the process.

We cannot just modify the evaluator to do this in the general case because the `ItemRecommender` interface does not guarantee that the results of a 5-item recommendation query are the first 5 results of a 10-item recommendation query. Custom metrics are free to take advantage of specific knowledge about the structure and behaviors of the recommenders that you are using, but the evaluation structure and default metrics need to be correct and safe in the face of more complex behavior.

**Comment by mdekstrand** [comment]
The new evaluation metric logic in LensKit 3.0 fixes this.
